const SPREADSHEET_ID='1Ur2A0wAGxjpfjShdWOuN_-qw7o1qB-AT3JaymrFANGY';
const SHEETS={CONFIG:'CONFIGURACOES',PARTICIPANTES:'PARTICIPANTES',OPERADORES:'OPERADORES',GRUPOS:'GRUPOS',JOGOS:'JOGOS',CLASSIFICACAO:'CLASSIFICACAO',MATA_MATA:'MATA_MATA',HISTORICO:'HISTORICO'};
const SESSION_TTL=21600;
const MAX_LOGIN_FAILS=5;
const LOGIN_BLOCK_SECONDS=900;

function doGet(e){
  try{
    const a=String((e&&e.parameter&&e.parameter.action)||'status').trim();
    if(a==='status')return jsonResponse_({ok:true,sistema:'Sistema de Torneio de Tênis de Mesa – Etec',torneio:getConfig_('NOME_TORNEIO'),statusInscricoes:getConfig_('STATUS_INSCRICOES'),tipoInscricao:getConfig_('TIPO_INSCRICAO'),valorInscricao:Number(getConfig_('VALOR_INSCRICAO')||0),categorias:categoriasPermitidas_()});
    if(a==='participantesPublicos')return jsonResponse_({ok:true,participantes:listarParticipantesPublicos_()});
    if(a==='torneioPublico')return jsonResponse_({ok:true,jogos:listarJogos_(),classificacao:listarClassificacao_(),grupos:listarGruposPublicos_(),fasesGrupos:listarEstadosFasesGrupos_(),mataMata:listarMataMata_()});
    if(a==='adminSessao')return jsonResponse_(adminSessao_(e.parameter.token));
    if(a==='participantesAdmin'){const s=exigirSessao_(e.parameter.token);return jsonResponse_({ok:true,usuario:s.usuario,participantes:listarParticipantesAdmin_()});}
    if(a==='adminOperadores'){const s=exigirSessao_(e.parameter.token,'ADMINISTRADOR');return jsonResponse_({ok:true,usuario:s.usuario,operadores:listarOperadores_()});}
    if(a==='sorteioEstado'){const s=exigirSessao_(e.parameter.token);return jsonResponse_({ok:true,usuario:s.usuario,estado:obterEstadoSorteio_(e.parameter.categoria)});}
    if(a==='jogosAdmin'){const s=exigirSessao_(e.parameter.token);return jsonResponse_({ok:true,usuario:s.usuario,jogos:listarJogos_(),classificacao:listarClassificacao_(),grupos:listarGruposPublicos_(),fasesGrupos:listarEstadosFasesGrupos_(),mataMata:listarMataMata_()});}
    return jsonResponse_({ok:false,erro:'ACAO_INVALIDA'});
  }catch(err){return erroJson_(err);}
}

function doPost(e){
  const lock=LockService.getScriptLock();
  try{
    lock.waitLock(10000);
    const p=parsePayload_(e),a=String(p.action||'inscricao').trim();
    if(a==='inscricao')return jsonResponse_(registrarInscricao_(p));
    if(a==='adminLogin')return jsonResponse_(adminLogin_(p));
    if(a==='adminLogout')return jsonResponse_(adminLogout_(p.token));
    if(a==='adminAtualizarParticipante'){const s=exigirSessao_(p.token);return jsonResponse_(adminAtualizarParticipante_(p,s.usuario));}
    if(a==='adminSalvarOperador'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(adminSalvarOperador_(p,s.usuario));}
    if(a==='adminStatusOperador'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(adminStatusOperador_(p,s.usuario));}
    if(a==='adminDefinirCabeca'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(adminDefinirCabeca_(p,s.usuario));}
    if(a==='sorteioIniciar'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(iniciarSorteio_(p,s.usuario));}
    if(a==='sorteioAdicionar'){const s=exigirSessao_(p.token);return jsonResponse_(adicionarAoGrupo_(p,s.usuario));}
    if(a==='sorteioRemover'){const s=exigirSessao_(p.token);return jsonResponse_(removerDoGrupo_(p,s.usuario));}
    if(a==='sorteioFinalizar'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(finalizarSorteio_(p,s.usuario));}
    if(a==='sorteioReiniciar'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(reiniciarSorteio_(p,s.usuario));}
    if(a==='jogoSalvarResultado'){const s=exigirSessao_(p.token);return jsonResponse_(salvarResultadoJogo_(p,s.usuario));}
    if(a==='faseGruposEncerrar'){const s=exigirSessao_(p.token);return jsonResponse_(encerrarFaseGrupos_(p,s.usuario));}
    if(a==='faseGruposReabrir'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(reabrirFaseGrupos_(p,s.usuario));}
    if(a==='salvarConfigCategoria'){const s=exigirSessao_(p.token,'ADMINISTRADOR');return jsonResponse_(salvarConfigCategoria_(p,s.usuario));}
    return jsonResponse_({ok:false,erro:'ACAO_INVALIDA'});
  }catch(err){return erroJson_(err);}
  finally{try{lock.releaseLock()}catch(_){}}
}

function adminLogin_(p){
  const email=normalizarEmail_(p.email),pin=String(p.pin||'').trim();
  if(!email||!pin)return {ok:false,erro:'CREDENCIAIS_OBRIGATORIAS',mensagem:'Informe e-mail e PIN.'};
  const cache=CacheService.getScriptCache(),k=loginFailKey_(email),falhas=Number(cache.get(k)||0);
  if(falhas>=MAX_LOGIN_FAILS)return {ok:false,erro:'LOGIN_BLOQUEADO',mensagem:'Muitas tentativas incorretas. Aguarde 15 minutos.'};
  const op=buscarOperadorPorEmail_(email);
  if(!op||op.status!=='ATIVO'||hashPin_(op.pinSalt,pin)!==op.pinHash){cache.put(k,String(falhas+1),LOGIN_BLOCK_SECONDS);return {ok:false,erro:'CREDENCIAIS_INVALIDAS',mensagem:'E-mail ou PIN incorretos.'};}
  cache.remove(k);const token=gerarToken_(),usuario={id:op.id,nome:op.nome,email:op.email,nivel:op.nivel};
  cache.put(sessionKey_(token),JSON.stringify({usuario}),SESSION_TTL);atualizarUltimoLogin_(op.linha);
  registrarHistorico_({usuario:op.email,perfil:op.nivel,acao:'LOGIN_ADMIN',entidade:'OPERADORES',idRegistro:op.id,valorAnterior:'',valorNovo:'LOGIN',observacoes:'Login no painel administrativo.'});
  return {ok:true,token,usuario,expiraEmSegundos:SESSION_TTL};
}
function adminSessao_(token){try{const s=exigirSessao_(token);return {ok:true,usuario:s.usuario,expiraEmSegundos:SESSION_TTL}}catch(_){return {ok:false,erro:'NAO_AUTORIZADO',mensagem:'Sessão inválida ou expirada.'}}}
function adminLogout_(token){if(token)CacheService.getScriptCache().remove(sessionKey_(token));return {ok:true,mensagem:'Sessão encerrada.'}}
function exigirSessao_(token,nivel){token=String(token||'').trim();if(!token)throw authError_();const cache=CacheService.getScriptCache(),raw=cache.get(sessionKey_(token));if(!raw)throw authError_();const s=JSON.parse(raw),op=buscarOperadorPorEmail_(s.usuario.email);if(!op||op.status!=='ATIVO')throw authError_();if(nivel&&op.nivel!==nivel)throw new Error('ACESSO_NEGADO|Você não possui permissão para esta função.');s.usuario={id:op.id,nome:op.nome,email:op.email,nivel:op.nivel};cache.put(sessionKey_(token),JSON.stringify(s),SESSION_TTL);return s}
function authError_(){return new Error('NAO_AUTORIZADO|Sessão inválida ou expirada.')}
function sessionKey_(t){return 'tm_session_'+t}
function loginFailKey_(e){return 'tm_fail_'+hashTexto_(e).slice(0,32)}
function gerarToken_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'')}

function registrarInscricao_(d){
  if(String(getConfig_('STATUS_INSCRICOES')||'').toUpperCase()!=='ABERTAS')return {ok:false,erro:'INSCRICOES_ENCERRADAS',mensagem:'As inscrições não estão abertas neste momento.'};
  const nome=limparTexto_(d.nomeCompleto||d.nome),turma=limparTexto_(d.turma),modulo=limparTexto_(d.modulo),email=normalizarEmail_(d.email),categoria=limparTexto_(d.categoria);
  if(!nome||!turma||!email||!categoria)return {ok:false,erro:'CAMPOS_OBRIGATORIOS',mensagem:'Preencha nome, turma, e-mail e categoria.'};
  if(!emailValido_(email))return {ok:false,erro:'EMAIL_INVALIDO',mensagem:'Informe um e-mail válido.'};
  if(!categoriasPermitidas_().includes(categoria))return {ok:false,erro:'CATEGORIA_INVALIDA',mensagem:'Selecione uma categoria válida.'};
  if(emailJaInscrito_(email))return {ok:false,erro:'EMAIL_JA_INSCRITO',mensagem:'Já existe uma inscrição vinculada a este e-mail.'};
  const tipo=String(getConfig_('TIPO_INSCRICAO')||'GRATUITA').toUpperCase(),valor=Number(getConfig_('VALOR_INSCRICAO')||0),id=gerarId_('P');
  gravarObjetoPrimeiraLinhaLivre_(SHEETS.PARTICIPANTES,'ID_PARTICIPANTE',{ID_PARTICIPANTE:id,DATA_INSCRICAO:new Date(),NOME_COMPLETO:nome,TURMA:turma,MODULO:modulo,EMAIL:email,CATEGORIA_ESCOLHIDA:categoria,CATEGORIA_VALIDADA:'',STATUS_REVISAO_CATEGORIA:'PENDENTE',STATUS_INSCRICAO:'PENDENTE_REVISAO',CABECA_DE_CHAVE:false,ORDEM_CABECA_CHAVE:'',RANKING_ANTES_TORNEIO:'',TIPO_INSCRICAO:tipo,VALOR_INSCRICAO:valor,STATUS_PAGAMENTO:tipo==='GRATUITA'?'ISENTO':'PENDENTE',COMPROVANTE_URL:'',OBSERVACOES:limparTexto_(d.observacoes),ATIVO:true});
  registrarHistorico_({usuario:email,perfil:'PARTICIPANTE',acao:'INSCRICAO_REALIZADA',entidade:'PARTICIPANTES',idRegistro:id,valorAnterior:'',valorNovo:JSON.stringify({nome,turma,categoriaEscolhida:categoria}),observacoes:'Inscrição realizada pelo formulário público.'});
  return {ok:true,idParticipante:id,status:'PENDENTE_REVISAO',categoriaEscolhida:categoria,mensagem:'Inscrição recebida com sucesso. A categoria será revisada pela organização.'};
}

function adminAtualizarParticipante_(d,usuario){
  const id=limparTexto_(d.idParticipante),cat=limparTexto_(d.categoriaValidada),st=limparTexto_(d.statusInscricao).toUpperCase();
  if(!id)return {ok:false,erro:'ID_OBRIGATORIO',mensagem:'Participante não informado.'};
  if(!categoriasPermitidas_().includes(cat))return {ok:false,erro:'CATEGORIA_INVALIDA',mensagem:'Categoria inválida.'};
  if(!['APROVADO','PENDENTE_REVISAO','CANCELADO'].includes(st))return {ok:false,erro:'STATUS_INVALIDO',mensagem:'Status inválido.'};
  const sh=getSheet_(SHEETS.PARTICIPANTES),idx=indexHeaders_(getHeaders_(sh)),linha=localizarLinhaPorValor_(sh,idx.ID_PARTICIPANTE+1,id);if(linha===-1)return {ok:false,erro:'PARTICIPANTE_NAO_ENCONTRADO',mensagem:'Participante não encontrado.'};
  const anterior={categoria:sh.getRange(linha,idx.CATEGORIA_VALIDADA+1).getValue(),status:sh.getRange(linha,idx.STATUS_INSCRICAO+1).getValue()};
  sh.getRange(linha,idx.CATEGORIA_VALIDADA+1).setValue(cat);sh.getRange(linha,idx.STATUS_INSCRICAO+1).setValue(st);sh.getRange(linha,idx.STATUS_REVISAO_CATEGORIA+1).setValue(st==='PENDENTE_REVISAO'?'PENDENTE':'REVISADO');
  registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'PARTICIPANTE_ATUALIZADO',entidade:'PARTICIPANTES',idRegistro:id,valorAnterior:JSON.stringify(anterior),valorNovo:JSON.stringify({categoria:cat,status:st}),observacoes:'Atualização pelo painel administrativo.'});
  return {ok:true,mensagem:'Participante atualizado com sucesso.'};
}

function adminDefinirCabeca_(d,usuario){
  const id=limparTexto_(d.idParticipante),ativo=String(d.cabecaDeChave).toLowerCase()==='true',ordem=ativo?Number(d.ordemCabecaChave):'';
  const p=obterParticipantesValidos_().find(x=>x.id===id);if(!p||!p.ativo||p.statusInscricao!=='APROVADO')return {ok:false,erro:'PARTICIPANTE_INVALIDO',mensagem:'O cabeça de chave deve ser um participante ativo e aprovado.'};
  const cat=p.categoriaValidada||p.categoriaEscolhida;if(obterLinhasGrupo_(cat).length)return {ok:false,erro:'SORTEIO_JA_INICIADO',mensagem:'Não é possível alterar cabeças de chave depois de iniciar o sorteio desta categoria.'};
  if(ativo&&(!Number.isInteger(ordem)||ordem<1))return {ok:false,erro:'ORDEM_INVALIDA',mensagem:'Informe uma ordem de cabeça de chave válida.'};
  if(ativo){const conflito=obterParticipantesValidos_().some(x=>x.id!==id&&x.ativo&&x.statusInscricao==='APROVADO'&&(x.categoriaValidada||x.categoriaEscolhida)===cat&&x.cabecaDeChave&&Number(x.ordemCabecaChave)===ordem);if(conflito)return {ok:false,erro:'ORDEM_DUPLICADA',mensagem:'Já existe outro cabeça de chave com essa ordem nesta categoria.'};}
  const sh=getSheet_(SHEETS.PARTICIPANTES),idx=indexHeaders_(getHeaders_(sh)),linha=localizarLinhaPorValor_(sh,idx.ID_PARTICIPANTE+1,id);sh.getRange(linha,idx.CABECA_DE_CHAVE+1).setValue(ativo);sh.getRange(linha,idx.ORDEM_CABECA_CHAVE+1).setValue(ativo?ordem:'');
  registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'CABECA_CHAVE_ATUALIZADO',entidade:'PARTICIPANTES',idRegistro:id,valorAnterior:'',valorNovo:JSON.stringify({cabecaDeChave:ativo,ordem:ativo?ordem:''}),observacoes:'Definição de cabeça de chave.'});
  return {ok:true,mensagem:ativo?'Cabeça de chave definido com sucesso.':'Participante removido dos cabeças de chave.'};
}

function obterEstadoSorteio_(categoria){
  categoria=limparTexto_(categoria);if(!categoriasPermitidas_().includes(categoria))throw new Error('CATEGORIA_INVALIDA|Categoria inválida.');
  const participantes=obterParticipantesValidos_().filter(p=>p.ativo&&p.statusInscricao==='APROVADO'&&(p.categoriaValidada||p.categoriaEscolhida)===categoria),linhas=obterLinhasGrupo_(categoria),ids=new Set(linhas.map(x=>x.idParticipante)),grupos={};
  linhas.forEach(x=>{if(!grupos[x.nomeGrupo])grupos[x.nomeGrupo]={idGrupo:x.idGrupo,nome:x.nomeGrupo,ordem:x.ordem,status:x.status,participantes:[]};grupos[x.nomeGrupo].participantes.push(x)});
  const cabecas=participantes.filter(p=>p.cabecaDeChave).sort((a,b)=>Number(a.ordemCabecaChave||999)-Number(b.ordemCabecaChave||999));
  let status='NAO_INICIADO';if(linhas.length)status=linhas.every(x=>x.status==='FINALIZADO')?'FINALIZADO':'EM_SORTEIO';
  return {categoria,status,totalParticipantes:participantes.length,cabecas,grupos:Object.values(grupos).sort((a,b)=>a.ordem-b.ordem),naoSorteados:participantes.filter(p=>!ids.has(p.id)&&!p.cabecaDeChave),todosParticipantes:participantes};
}
function iniciarSorteio_(d,usuario){
  const categoria=limparTexto_(d.categoria);if(!categoriasPermitidas_().includes(categoria))return {ok:false,erro:'CATEGORIA_INVALIDA',mensagem:'Categoria inválida.'};if(obterLinhasGrupo_(categoria).length)return {ok:false,erro:'SORTEIO_EXISTENTE',mensagem:'O sorteio desta categoria já foi iniciado.'};
  const ps=obterParticipantesValidos_().filter(p=>p.ativo&&p.statusInscricao==='APROVADO'&&(p.categoriaValidada||p.categoriaEscolhida)===categoria),cabecas=ps.filter(p=>p.cabecaDeChave).sort((a,b)=>Number(a.ordemCabecaChave)-Number(b.ordemCabecaChave));
  if(cabecas.length<2)return {ok:false,erro:'CABECAS_INSUFICIENTES',mensagem:'Defina pelo menos 2 cabeças de chave nesta categoria antes de iniciar o sorteio.'};
  const ordens=new Set(cabecas.map(p=>Number(p.ordemCabecaChave)));if(ordens.size!==cabecas.length||[...ordens].some(n=>!Number.isInteger(n)||n<1))return {ok:false,erro:'ORDEM_CABECAS_INVALIDA',mensagem:'As ordens dos cabeças de chave precisam ser únicas e válidas.'};
  cabecas.forEach((p,i)=>{const letra=letraGrupo_(i),nome='Grupo '+letra;gravarObjetoPrimeiraLinhaLivre_(SHEETS.GRUPOS,'ID_GRUPO',{ID_GRUPO:'GR-'+slugCategoria_(categoria)+'-'+letra,CATEGORIA:categoria,NOME_GRUPO:nome,ORDEM:i+1,ID_PARTICIPANTE:p.id,NOME_PARTICIPANTE:p.nome,POSICAO_SORTEIO:0,CABECA_DE_CHAVE:true,DATA_GERACAO:new Date(),STATUS:'EM_SORTEIO'})});
  registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'SORTEIO_INICIADO',entidade:'GRUPOS',idRegistro:categoria,valorAnterior:'',valorNovo:JSON.stringify({grupos:cabecas.length}),observacoes:'Cabeças de chave posicionados automaticamente, um por grupo.'});return {ok:true,mensagem:'Sorteio iniciado. Os cabeças de chave já foram posicionados nos grupos.'};
}
function adicionarAoGrupo_(d,usuario){
  const categoria=limparTexto_(d.categoria),id=limparTexto_(d.idParticipante),nomeGrupo=limparTexto_(d.nomeGrupo),estado=obterEstadoSorteio_(categoria);if(estado.status!=='EM_SORTEIO')return {ok:false,erro:'SORTEIO_NAO_ABERTO',mensagem:'O sorteio desta categoria não está aberto.'};const p=estado.naoSorteados.find(x=>x.id===id);if(!p)return {ok:false,erro:'PARTICIPANTE_INDISPONIVEL',mensagem:'Participante não disponível para sorteio.'};const g=estado.grupos.find(x=>x.nome===nomeGrupo);if(!g)return {ok:false,erro:'GRUPO_INVALIDO',mensagem:'Grupo inválido.'};const pos=obterLinhasGrupo_(categoria).filter(x=>!x.cabecaDeChave).length+1;
  gravarObjetoPrimeiraLinhaLivre_(SHEETS.GRUPOS,'ID_GRUPO',{ID_GRUPO:g.idGrupo,CATEGORIA:categoria,NOME_GRUPO:g.nome,ORDEM:g.ordem,ID_PARTICIPANTE:p.id,NOME_PARTICIPANTE:p.nome,POSICAO_SORTEIO:pos,CABECA_DE_CHAVE:false,DATA_GERACAO:new Date(),STATUS:'EM_SORTEIO'});registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'PARTICIPANTE_SORTEADO',entidade:'GRUPOS',idRegistro:p.id,valorAnterior:'',valorNovo:g.nome,observacoes:'Participante lançado durante sorteio ao vivo.'});return {ok:true,mensagem:p.nome+' inserido no '+g.nome+'.'};
}
function removerDoGrupo_(d,usuario){
  const categoria=limparTexto_(d.categoria),id=limparTexto_(d.idParticipante),estado=obterEstadoSorteio_(categoria);if(estado.status!=='EM_SORTEIO')return {ok:false,erro:'SORTEIO_NAO_ABERTO',mensagem:'O sorteio não está aberto.'};
  const sh=getSheet_(SHEETS.GRUPOS),idx=indexHeaders_(getHeaders_(sh)),max=sh.getMaxRows(),vals=sh.getRange(2,1,max-1,sh.getLastColumn()).getValues();let linha=-1,row=null;for(let i=0;i<vals.length;i++){if(String(vals[i][idx.CATEGORIA])===categoria&&String(vals[i][idx.ID_PARTICIPANTE])===id){linha=i+2;row=vals[i];break}}
  if(linha===-1)return {ok:false,erro:'NAO_ENCONTRADO',mensagem:'Participante não encontrado nos grupos.'};if(row[idx.CABECA_DE_CHAVE]===true||String(row[idx.CABECA_DE_CHAVE]).toUpperCase()==='TRUE')return {ok:false,erro:'CABECA_FIXO',mensagem:'Cabeças de chave não podem ser removidos durante o sorteio.'};sh.getRange(linha,1,1,sh.getLastColumn()).clearContent();registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'SORTEIO_CORRIGIDO',entidade:'GRUPOS',idRegistro:id,valorAnterior:String(row[idx.NOME_GRUPO]),valorNovo:'REMOVIDO',observacoes:'Correção durante sorteio ao vivo.'});return {ok:true,mensagem:'Participante devolvido à lista de não sorteados.'};
}
function finalizarSorteio_(d,usuario){
  const categoria=limparTexto_(d.categoria),estado=obterEstadoSorteio_(categoria);if(estado.status!=='EM_SORTEIO')return {ok:false,erro:'SORTEIO_NAO_ABERTO',mensagem:'O sorteio desta categoria não está aberto.'};if(estado.naoSorteados.length)return {ok:false,erro:'PARTICIPANTES_PENDENTES',mensagem:'Ainda existem '+estado.naoSorteados.length+' participante(s) não sorteado(s).'};
  const sh=getSheet_(SHEETS.GRUPOS),idx=indexHeaders_(getHeaders_(sh)),max=sh.getMaxRows(),vals=sh.getRange(2,1,max-1,sh.getLastColumn()).getValues();for(let i=0;i<vals.length;i++){if(String(vals[i][idx.CATEGORIA])===categoria&&String(vals[i][idx.ID_PARTICIPANTE]||'').trim())sh.getRange(i+2,idx.STATUS+1).setValue('FINALIZADO')}
  gerarJogosDosGrupos_(categoria,usuario);recalcularClassificacaoCategoria_(categoria);registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'SORTEIO_FINALIZADO',entidade:'GRUPOS',idRegistro:categoria,valorAnterior:'EM_SORTEIO',valorNovo:'FINALIZADO',observacoes:'Grupos bloqueados e confrontos gerados automaticamente.'});return {ok:true,mensagem:'Sorteio finalizado. Os grupos foram bloqueados e os confrontos foram gerados.'};
}
function reiniciarSorteio_(d,usuario){const categoria=limparTexto_(d.categoria),estado=obterEstadoSorteio_(categoria);if(estado.status==='FINALIZADO')return {ok:false,erro:'SORTEIO_FINALIZADO',mensagem:'O sorteio já foi finalizado. Não é permitido reiniciar após a geração dos confrontos.'};limparLinhasPorCategoria_(SHEETS.GRUPOS,categoria,'CATEGORIA');registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'SORTEIO_REINICIADO',entidade:'GRUPOS',idRegistro:categoria,valorAnterior:'EM_SORTEIO',valorNovo:'NAO_INICIADO',observacoes:'Sorteio apagado antes da finalização.'});return {ok:true,mensagem:'Sorteio reiniciado. Os cabeças de chave continuam definidos nos participantes.'}}

function gerarJogosDosGrupos_(categoria,usuario){
  if(obterJogosCategoria_(categoria).length)throw new Error('JOGOS_EXISTENTES|Já existem confrontos de grupos para esta categoria.');
  const estado=obterEstadoSorteio_(categoria);estado.grupos.forEach(g=>{const jogadores=g.participantes.slice().sort((a,b)=>(a.cabecaDeChave?-1:1)-(b.cabecaDeChave?-1:1)||Number(a.posicaoSorteio)-Number(b.posicaoSorteio)),rodadas=gerarRodadasRoundRobin_(jogadores);rodadas.forEach((pares,r)=>pares.forEach(par=>{if(!par[0]||!par[1])return;gravarObjetoPrimeiraLinhaLivre_(SHEETS.JOGOS,'ID_JOGO',{ID_JOGO:gerarId_('J'),CATEGORIA:categoria,FASE:'GRUPOS',GRUPO:g.nome,RODADA:r+1,DATA:'',HORARIO_PREVISTO:'',MESA:'',ID_JOGADOR_A:par[0].idParticipante,JOGADOR_A:par[0].nomeParticipante,ID_JOGADOR_B:par[1].idParticipante,JOGADOR_B:par[1].nomeParticipante,SET1_A:'',SET1_B:'',SET2_A:'',SET2_B:'',SET3_A:'',SET3_B:'',SETS_A:'',SETS_B:'',PONTOS_A:'',PONTOS_B:'',ID_VENCEDOR:'',VENCEDOR:'',STATUS:'AGENDADO',OPERADOR_LANCAMENTO:'',DATA_HORA_LANCAMENTO:'',OBSERVACOES:'',SET4_A:'',SET4_B:'',SET5_A:'',SET5_B:'',TIPO_RESULTADO:'',MELHOR_DE:3})}))});
}
function gerarRodadasRoundRobin_(jogadores){let a=jogadores.slice();if(a.length%2)a.push(null);const n=a.length,rodadas=[];for(let r=0;r<n-1;r++){const pares=[];for(let i=0;i<n/2;i++)pares.push([a[i],a[n-1-i]]);rodadas.push(pares);a=[a[0],a[n-1]].concat(a.slice(1,n-1))}return rodadas}
function obterJogosCategoria_(categoria){return listarJogos_().filter(j=>j.categoria===categoria&&j.fase==='GRUPOS')}
function melhorDePorFase_(fase){fase=String(fase||'').toUpperCase();return ['SEMIFINAL','SEMIFINAIS','FINAL','TERCEIRO_LUGAR','3_LUGAR','DECISAO_3_LUGAR'].includes(fase)?5:3}

function listarJogos_(){
  const sh=getSheet_(SHEETS.JOGOS),h=getHeaders_(sh),idx=indexHeaders_(h),last=sh.getLastRow();if(last<2)return [];
  return sh.getRange(2,1,last-1,h.length).getValues().filter(r=>String(r[idx.ID_JOGO]||'').trim()).map(r=>({id:r[idx.ID_JOGO],categoria:r[idx.CATEGORIA],fase:String(r[idx.FASE]||''),grupo:r[idx.GRUPO],rodada:Number(r[idx.RODADA]||0),data:r[idx.DATA],horario:r[idx.HORARIO_PREVISTO],mesa:r[idx.MESA],idA:r[idx.ID_JOGADOR_A],jogadorA:r[idx.JOGADOR_A],idB:r[idx.ID_JOGADOR_B],jogadorB:r[idx.JOGADOR_B],sets:[[r[idx.SET1_A],r[idx.SET1_B]],[r[idx.SET2_A],r[idx.SET2_B]],[r[idx.SET3_A],r[idx.SET3_B]],[idx.SET4_A!==undefined?r[idx.SET4_A]:'',idx.SET4_B!==undefined?r[idx.SET4_B]:''],[idx.SET5_A!==undefined?r[idx.SET5_A]:'',idx.SET5_B!==undefined?r[idx.SET5_B]:'']],setsA:Number(r[idx.SETS_A]||0),setsB:Number(r[idx.SETS_B]||0),pontosA:Number(r[idx.PONTOS_A]||0),pontosB:Number(r[idx.PONTOS_B]||0),idVencedor:r[idx.ID_VENCEDOR],vencedor:r[idx.VENCEDOR],status:String(r[idx.STATUS]||'AGENDADO'),operador:r[idx.OPERADOR_LANCAMENTO],dataHoraLancamento:r[idx.DATA_HORA_LANCAMENTO],observacoes:r[idx.OBSERVACOES],tipoResultado:idx.TIPO_RESULTADO!==undefined?String(r[idx.TIPO_RESULTADO]||''):'',melhorDe:idx.MELHOR_DE!==undefined?Number(r[idx.MELHOR_DE]||melhorDePorFase_(r[idx.FASE])):melhorDePorFase_(r[idx.FASE])}));
}

function salvarResultadoJogo_(d,usuario){
  const id=limparTexto_(d.idJogo),tipo=String(d.tipoResultado||'NORMAL').toUpperCase();if(!id)return {ok:false,erro:'JOGO_OBRIGATORIO',mensagem:'Partida não informada.'};if(!['NORMAL','WO_A','WO_B','WO_DUPLO'].includes(tipo))return {ok:false,erro:'TIPO_RESULTADO_INVALIDO',mensagem:'Tipo de resultado inválido.'};
  const sh=getSheet_(SHEETS.JOGOS),h=getHeaders_(sh),idx=indexHeaders_(h),linha=localizarLinhaPorValor_(sh,idx.ID_JOGO+1,id);if(linha===-1)return {ok:false,erro:'JOGO_NAO_ENCONTRADO',mensagem:'Partida não encontrada.'};
  const r=sh.getRange(linha,1,1,h.length).getValues()[0],fase=String(r[idx.FASE]||''),categoria=String(r[idx.CATEGORIA]||''),statusAnterior=String(r[idx.STATUS]||''),melhorDe=melhorDePorFase_(fase);
  if(fase==='GRUPOS'&&obterEstadoFaseGrupos_(categoria).encerrada)return {ok:false,erro:'FASE_GRUPOS_ENCERRADA',mensagem:'A fase de grupos desta categoria já foi encerrada. O administrador precisa reabri-la antes de corrigir resultados.'};
  if(statusAnterior==='FINALIZADO'&&fase!=='GRUPOS'){
    if(usuario.nivel!=='ADMINISTRADOR')return {ok:false,erro:'CORRECAO_RESTRITA',mensagem:'No mata-mata, somente o administrador pode corrigir uma partida finalizada.'};
    if(existeFasePosteriorGerada_(categoria,fase))return {ok:false,erro:'FASE_POSTERIOR_GERADA',mensagem:'A fase seguinte já foi gerada. Para preservar a chave, este resultado não pode mais ser alterado.'};
  }
  const anterior=serializarJogoLinha_(r,idx),resultado=montarResultado_(d,tipo,melhorDe,{idA:r[idx.ID_JOGADOR_A],nomeA:r[idx.JOGADOR_A],idB:r[idx.ID_JOGADOR_B],nomeB:r[idx.JOGADOR_B]});
  const campos={SET1_A:resultado.sets[0][0],SET1_B:resultado.sets[0][1],SET2_A:resultado.sets[1][0],SET2_B:resultado.sets[1][1],SET3_A:resultado.sets[2][0],SET3_B:resultado.sets[2][1],SETS_A:resultado.setsA,SETS_B:resultado.setsB,PONTOS_A:resultado.pontosA,PONTOS_B:resultado.pontosB,ID_VENCEDOR:resultado.idVencedor,VENCEDOR:resultado.vencedor,STATUS:'FINALIZADO',OPERADOR_LANCAMENTO:usuario.email,DATA_HORA_LANCAMENTO:new Date(),OBSERVACOES:limparTexto_(d.observacoes),SET4_A:resultado.sets[3][0],SET4_B:resultado.sets[3][1],SET5_A:resultado.sets[4][0],SET5_B:resultado.sets[4][1],TIPO_RESULTADO:tipo,MELHOR_DE:melhorDe};
  Object.keys(campos).forEach(k=>{if(idx[k]!==undefined)sh.getRange(linha,idx[k]+1).setValue(campos[k])});
  if(fase==='GRUPOS')recalcularClassificacaoCategoria_(categoria);else{sincronizarConfrontoResultado_(id,resultado);avancarMataMataSePronto_(categoria,fase,usuario);}
  registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:statusAnterior==='FINALIZADO'?'RESULTADO_CORRIGIDO':'RESULTADO_LANCADO',entidade:'JOGOS',idRegistro:id,valorAnterior:JSON.stringify(anterior),valorNovo:JSON.stringify(campos),observacoes:statusAnterior==='FINALIZADO'?'Resultado corrigido.':'Resultado finalizado.'});
  return {ok:true,mensagem:statusAnterior==='FINALIZADO'?'Resultado corrigido com sucesso.':'Partida finalizada com sucesso.',classificacao:listarClassificacao_().filter(x=>x.categoria===categoria&&x.grupo===String(r[idx.GRUPO])),mataMata:listarMataMata_().filter(x=>x.categoria===categoria)};
}
function montarResultado_(d,tipo,melhorDe,j){
  const alvo=melhorDe===5?3:2,sets=[['',''],['',''],['',''],['',''],['','']];
  if(tipo==='WO_DUPLO')return {sets,setsA:0,setsB:0,pontosA:0,pontosB:0,idVencedor:'',vencedor:'',idPerdedor:'',perdedor:''};
  if(tipo==='WO_A'||tipo==='WO_B'){const aVence=tipo==='WO_B';for(let i=0;i<alvo;i++)sets[i]=aVence?[11,0]:[0,11];return {sets,setsA:aVence?alvo:0,setsB:aVence?0:alvo,pontosA:aVence?11*alvo:0,pontosB:aVence?0:11*alvo,idVencedor:aVence?j.idA:j.idB,vencedor:aVence?j.nomeA:j.nomeB,idPerdedor:aVence?j.idB:j.idA,perdedor:aVence?j.nomeB:j.nomeA};}
  let va=0,vb=0,pa=0,pb=0,encerrou=false;
  for(let i=0;i<melhorDe;i++){
    const sa=String(d['set'+(i+1)+'A']??'').trim(),sb=String(d['set'+(i+1)+'B']??'').trim();if(sa===''&&sb==='')continue;if(encerrou)throw new Error('SETS_EXCEDENTES|Não informe sets depois que um jogador já alcançou a quantidade necessária para vencer.');if(sa===''||sb===''||isNaN(Number(sa))||isNaN(Number(sb)))throw new Error('PLACAR_INVALIDO|Informe os dois pontos de cada set disputado.');const a=Number(sa),b=Number(sb),ma=Math.max(a,b),mi=Math.min(a,b);if(a<0||b<0||a===b||ma<11||ma-mi<2)throw new Error('SET_INVALIDO|Cada set termina com no mínimo 11 pontos e diferença mínima de 2.');if(mi<=9&&ma!==11)throw new Error('SET_INVALIDO|Com o perdedor até 9 pontos, o set deve terminar em 11.');if(mi>=10&&ma!==mi+2)throw new Error('SET_INVALIDO|Depois de 10 x 10, o set termina somente com diferença exata de 2 pontos.');sets[i]=[a,b];pa+=a;pb+=b;if(a>b)va++;else vb++;if(va===alvo||vb===alvo)encerrou=true;
  }
  if(va!==alvo&&vb!==alvo)throw new Error('PARTIDA_INCOMPLETA|Informe os sets necessários até um jogador vencer a partida.');const aVence=va>vb;return {sets,setsA:va,setsB:vb,pontosA:pa,pontosB:pb,idVencedor:aVence?j.idA:j.idB,vencedor:aVence?j.nomeA:j.nomeB,idPerdedor:aVence?j.idB:j.idA,perdedor:aVence?j.nomeB:j.nomeA};
}
function serializarJogoLinha_(r,idx){return {set1:[r[idx.SET1_A],r[idx.SET1_B]],set2:[r[idx.SET2_A],r[idx.SET2_B]],set3:[r[idx.SET3_A],r[idx.SET3_B]],set4:idx.SET4_A!==undefined?[r[idx.SET4_A],r[idx.SET4_B]]:[],set5:idx.SET5_A!==undefined?[r[idx.SET5_A],r[idx.SET5_B]]:[],setsA:r[idx.SETS_A],setsB:r[idx.SETS_B],pontosA:r[idx.PONTOS_A],pontosB:r[idx.PONTOS_B],vencedor:r[idx.VENCEDOR],status:r[idx.STATUS],tipoResultado:idx.TIPO_RESULTADO!==undefined?r[idx.TIPO_RESULTADO]:''}}

function recalcularClassificacaoCategoria_(categoria){
  limparLinhasPorCategoria_(SHEETS.CLASSIFICACAO,categoria,'CATEGORIA');const membros=obterLinhasGrupo_(categoria),jogos=listarJogos_().filter(j=>j.categoria===categoria&&j.fase==='GRUPOS'&&j.status==='FINALIZADO'),porGrupo={},qtdClass=getClassificadosPorGrupo_(categoria),criterio=String(getConfig_('CRITERIOS_DESEMPATE')||'Vitórias > confronto direto > saldo de sets > saldo de pontos > sets vencidos > pontos marcados > sorteio');
  membros.forEach(m=>{if(!porGrupo[m.nomeGrupo])porGrupo[m.nomeGrupo]={};porGrupo[m.nomeGrupo][m.idParticipante]={categoria,grupo:m.nomeGrupo,id:m.idParticipante,nome:m.nomeParticipante,jogos:0,vitorias:0,derrotas:0,setsPro:0,setsContra:0,pontosPro:0,pontosContra:0}});
  jogos.forEach(j=>{const g=porGrupo[j.grupo];if(!g||!g[j.idA]||!g[j.idB])return;const a=g[j.idA],b=g[j.idB];a.jogos++;b.jogos++;if(j.tipoResultado!=='WO_DUPLO'){if(j.idVencedor===j.idA){a.vitorias++;b.derrotas++}else if(j.idVencedor===j.idB){b.vitorias++;a.derrotas++}}a.setsPro+=j.setsA;a.setsContra+=j.setsB;b.setsPro+=j.setsB;b.setsContra+=j.setsA;a.pontosPro+=j.pontosA;a.pontosContra+=j.pontosB;b.pontosPro+=j.pontosB;b.pontosContra+=j.pontosA});
  Object.keys(porGrupo).sort().forEach(grupo=>{const lista=Object.values(porGrupo[grupo]),jg=jogos.filter(j=>j.grupo===grupo);ordenarClassificacaoGrupo_(lista,jg);lista.forEach((x,i)=>{const saldoSets=x.setsPro-x.setsContra,saldoPontos=x.pontosPro-x.pontosContra,aprov=x.jogos?x.vitorias/x.jogos:0;gravarObjetoPrimeiraLinhaLivre_(SHEETS.CLASSIFICACAO,'CATEGORIA',{CATEGORIA:categoria,GRUPO:grupo,ID_PARTICIPANTE:x.id,NOME:x.nome,JOGOS:x.jogos,VITORIAS:x.vitorias,DERROTAS:x.derrotas,SETS_PRO:x.setsPro,SETS_CONTRA:x.setsContra,SALDO_SETS:saldoSets,PONTOS_PRO:x.pontosPro,PONTOS_CONTRA:x.pontosContra,SALDO_PONTOS:saldoPontos,APROVEITAMENTO:aprov,POSICAO:i+1,CLASSIFICADO:i<Math.min(qtdClass,lista.length),CRITERIO_DESEMPATE:criterio});});});
}
function ordenarClassificacaoGrupo_(lista,jogos){
  lista.sort((a,b)=>b.vitorias-a.vitorias);const saida=[];let i=0;
  while(i<lista.length){let j=i+1;while(j<lista.length&&lista[j].vitorias===lista[i].vitorias)j++;const bloco=lista.slice(i,j);if(bloco.length===2){const a=bloco[0],b=bloco[1],direto=jogos.find(x=>x.tipoResultado!=='WO_DUPLO'&&((x.idA===a.id&&x.idB===b.id)||(x.idA===b.id&&x.idB===a.id)));if(direto&&direto.idVencedor){bloco.sort((x,y)=>x.id===direto.idVencedor?-1:y.id===direto.idVencedor?1:comparadorGeral_(x,y));}else bloco.sort(comparadorGeral_);}else if(bloco.length>2){const ids=new Set(bloco.map(x=>x.id)),mini={};bloco.forEach(x=>mini[x.id]={v:0,sp:0,sc:0,pp:0,pc:0});jogos.filter(x=>ids.has(x.idA)&&ids.has(x.idB)).forEach(x=>{const a=mini[x.idA],b=mini[x.idB];if(x.tipoResultado!=='WO_DUPLO'){if(x.idVencedor===x.idA)a.v++;else if(x.idVencedor===x.idB)b.v++;}a.sp+=x.setsA;a.sc+=x.setsB;b.sp+=x.setsB;b.sc+=x.setsA;a.pp+=x.pontosA;a.pc+=x.pontosB;b.pp+=x.pontosB;b.pc+=x.pontosA});bloco.sort((a,b)=>{const ma=mini[a.id],mb=mini[b.id];return mb.v-ma.v||((mb.sp-mb.sc)-(ma.sp-ma.sc))||((mb.pp-mb.pc)-(ma.pp-ma.pc))||comparadorGeral_(a,b)});}saida.push.apply(saida,bloco);i=j;}
  lista.splice(0,lista.length,...saida);
}
function comparadorGeral_(a,b){return ((b.setsPro-b.setsContra)-(a.setsPro-a.setsContra))||((b.pontosPro-b.pontosContra)-(a.pontosPro-a.pontosContra))||b.setsPro-a.setsPro||b.pontosPro-a.pontosPro||String(a.nome).localeCompare(String(b.nome),'pt-BR')}
function listarClassificacao_(){const sh=getSheet_(SHEETS.CLASSIFICACAO),h=getHeaders_(sh),idx=indexHeaders_(h),last=sh.getLastRow();if(last<2)return [];return sh.getRange(2,1,last-1,h.length).getValues().filter(r=>String(r[idx.CATEGORIA]||'').trim()&&String(r[idx.ID_PARTICIPANTE]||'').trim()).map(r=>({categoria:r[idx.CATEGORIA],grupo:r[idx.GRUPO],id:r[idx.ID_PARTICIPANTE],nome:r[idx.NOME],jogos:Number(r[idx.JOGOS]||0),vitorias:Number(r[idx.VITORIAS]||0),derrotas:Number(r[idx.DERROTAS]||0),setsPro:Number(r[idx.SETS_PRO]||0),setsContra:Number(r[idx.SETS_CONTRA]||0),saldoSets:Number(r[idx.SALDO_SETS]||0),pontosPro:Number(r[idx.PONTOS_PRO]||0),pontosContra:Number(r[idx.PONTOS_CONTRA]||0),saldoPontos:Number(r[idx.SALDO_PONTOS]||0),aproveitamento:Number(r[idx.APROVEITAMENTO]||0),posicao:Number(r[idx.POSICAO]||0),classificado:r[idx.CLASSIFICADO]===true||String(r[idx.CLASSIFICADO]).toUpperCase()==='TRUE',criterio:r[idx.CRITERIO_DESEMPATE]})).sort((a,b)=>String(a.categoria).localeCompare(String(b.categoria))||String(a.grupo).localeCompare(String(b.grupo))||a.posicao-b.posicao)}

function obterEstadoFaseGrupos_(categoria){
  categoria=limparTexto_(categoria);const jogos=listarJogos_().filter(j=>j.categoria===categoria&&j.fase==='GRUPOS'),finalizados=jogos.filter(j=>j.status==='FINALIZADO').length,membros=obterLinhasGrupo_(categoria),grupos=[...new Set(membros.map(x=>x.nomeGrupo))],tamanhos=grupos.map(g=>membros.filter(x=>x.nomeGrupo===g).length),mata=listarMataMata_().filter(x=>x.categoria===categoria),encerrada=mata.length>0||listarJogos_().some(j=>j.categoria===categoria&&j.fase!=='GRUPOS');
  let status='SEM_JOGOS';if(jogos.length)status=encerrada?'ENCERRADA':finalizados===jogos.length?'PRONTA_ENCERRAR':'EM_ANDAMENTO';
  return {categoria,status,totalJogos:jogos.length,jogosFinalizados:finalizados,jogosPendentes:jogos.length-finalizados,encerrada,podeEncerrar:!encerrada&&jogos.length>0&&finalizados===jogos.length,podeReabrir:encerrada&&!listarJogos_().some(j=>j.categoria===categoria&&j.fase!=='GRUPOS'&&j.status==='FINALIZADO'),classificadosPorGrupo:getClassificadosPorGrupo_(categoria),maxClassificados:tamanhos.length?Math.min.apply(null,tamanhos):0,grupos:grupos.length};
}
function listarEstadosFasesGrupos_(){return categoriasPermitidas_().map(obterEstadoFaseGrupos_)}
function salvarConfigCategoria_(d,usuario){const categoria=limparTexto_(d.categoria),qtd=Number(d.classificadosPorGrupo);if(!categoriasPermitidas_().includes(categoria))return {ok:false,erro:'CATEGORIA_INVALIDA',mensagem:'Categoria inválida.'};const estado=obterEstadoFaseGrupos_(categoria);if(estado.encerrada)return {ok:false,erro:'FASE_ENCERRADA',mensagem:'Reabra a fase de grupos antes de alterar esta configuração.'};if(!Number.isInteger(qtd)||qtd<1)return {ok:false,erro:'VALOR_INVALIDO',mensagem:'Informe ao menos 1 classificado por grupo.'};if(estado.maxClassificados&&qtd>estado.maxClassificados)return {ok:false,erro:'VALOR_INVALIDO',mensagem:'Nesta categoria, o menor grupo possui '+estado.maxClassificados+' participante(s).'};const chave='CLASSIFICADOS_POR_GRUPO_'+configKeyCategoria_(categoria),ant=getConfig_(chave)||getConfig_('CLASSIFICADOS_POR_GRUPO');setConfig_(chave,qtd,'Quantidade que avança por grupo na categoria '+categoria+'; alterável sem mudar o código');recalcularClassificacaoCategoria_(categoria);registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'CONFIG_MATA_MATA_ALTERADA',entidade:'CONFIGURACOES',idRegistro:categoria,valorAnterior:String(ant),valorNovo:String(qtd),observacoes:'Classificados por grupo alterado.'});return {ok:true,mensagem:'Configuração atualizada. '+qtd+' participante(s) por grupo avançarão nesta categoria.'}}
function encerrarFaseGrupos_(d,usuario){
  const categoria=limparTexto_(d.categoria);if(!categoriasPermitidas_().includes(categoria))return {ok:false,erro:'CATEGORIA_INVALIDA',mensagem:'Categoria inválida.'};const estado=obterEstadoFaseGrupos_(categoria);if(estado.encerrada)return {ok:false,erro:'FASE_JA_ENCERRADA',mensagem:'A fase de grupos desta categoria já foi encerrada.'};if(!estado.totalJogos)return {ok:false,erro:'SEM_JOGOS',mensagem:'Ainda não existem partidas de grupos nesta categoria.'};if(estado.jogosPendentes>0)return {ok:false,erro:'JOGOS_PENDENTES',mensagem:'Ainda faltam '+estado.jogosPendentes+' partida(s) desta categoria.'};
  recalcularClassificacaoCategoria_(categoria);const classificados=listarClassificacao_().filter(x=>x.categoria===categoria&&x.classificado);if(classificados.length<2)return {ok:false,erro:'CLASSIFICADOS_INSUFICIENTES',mensagem:'É necessário ter pelo menos dois classificados para gerar o mata-mata.'};gerarPrimeiraFaseMataMata_(categoria,classificados,usuario);registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'FASE_GRUPOS_ENCERRADA',entidade:'MATA_MATA',idRegistro:categoria,valorAnterior:'EM_ANDAMENTO',valorNovo:'ENCERRADA',observacoes:'Classificação congelada e mata-mata gerado sem aguardar a outra categoria.'});return {ok:true,mensagem:'Fase de grupos de '+categoria+' encerrada. O mata-mata foi gerado.',estado:obterEstadoFaseGrupos_(categoria),mataMata:listarMataMata_().filter(x=>x.categoria===categoria)};
}
function reabrirFaseGrupos_(d,usuario){const categoria=limparTexto_(d.categoria);if(!categoriasPermitidas_().includes(categoria))return {ok:false,erro:'CATEGORIA_INVALIDA',mensagem:'Categoria inválida.'};const estado=obterEstadoFaseGrupos_(categoria);if(!estado.encerrada)return {ok:false,erro:'FASE_NAO_ENCERRADA',mensagem:'A fase de grupos ainda não foi encerrada.'};if(!estado.podeReabrir)return {ok:false,erro:'MATA_MATA_JA_INICIADO',mensagem:'Já existe partida do mata-mata finalizada. A fase de grupos não pode ser reaberta automaticamente.'};limparJogosMataMataCategoria_(categoria);limparLinhasPorCategoria_(SHEETS.MATA_MATA,categoria,'CATEGORIA');recalcularClassificacaoCategoria_(categoria);registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'FASE_GRUPOS_REABERTA',entidade:'MATA_MATA',idRegistro:categoria,valorAnterior:'ENCERRADA',valorNovo:'EM_ANDAMENTO',observacoes:'Mata-mata ainda não iniciado foi removido para permitir correções.'});return {ok:true,mensagem:'Fase de grupos reaberta. Os resultados de grupo podem ser corrigidos novamente.'}}

function gerarPrimeiraFaseMataMata_(categoria,classificados,usuario){
  limparJogosMataMataCategoria_(categoria);limparLinhasPorCategoria_(SHEETS.MATA_MATA,categoria,'CATEGORIA');
  const ordenados=classificados.slice().sort(comparadorSeed_),q=ordenados.length,tamanho=proximaPotencia2_(q),byes=tamanho-q,fase=fasePorQuantidade_(tamanho),restantes=ordenados.slice(),confrontos=[];
  for(let i=0;i<byes;i++){const p=restantes.shift();confrontos.push({a:p,b:null,origemA:p.posicao+'º '+p.grupo,origemB:'BYE'});}
  while(restantes.length){const a=restantes.shift();let k=-1;for(let i=restantes.length-1;i>=0;i--){if(restantes[i].grupo!==a.grupo){k=i;break}}if(k<0)k=restantes.length-1;const b=restantes.splice(k,1)[0];confrontos.push({a,b,origemA:a.posicao+'º '+a.grupo,origemB:b.posicao+'º '+b.grupo});}
  confrontos.forEach((c,i)=>criarConfronto_(categoria,fase,i+1,c.a,c.b,c.origemA,c.origemB,'Primeira fase eliminatória gerada automaticamente.'));
  if(confrontos.every(c=>!c.b))avancarMataMataSePronto_(categoria,fase,usuario);
}
function comparadorSeed_(a,b){return a.posicao-b.posicao||b.vitorias-a.vitorias||b.saldoSets-a.saldoSets||b.saldoPontos-a.saldoPontos||String(a.nome).localeCompare(String(b.nome),'pt-BR')}
function proximaPotencia2_(n){let p=1;while(p<n)p*=2;return p}
function fasePorQuantidade_(q){if(q<=2)return 'FINAL';if(q<=4)return 'SEMIFINAL';if(q<=8)return 'QUARTAS_DE_FINAL';if(q<=16)return 'OITAVAS_DE_FINAL';if(q<=32)return 'DEZESSEIS_AVOS';return 'MATA_MATA_'+q}
function criarConfronto_(categoria,fase,ordem,a,b,origemA,origemB,obs){
  const idConfronto=gerarId_('MM'),agora=new Date();let idJogo='',status='AGENDADO',idVencedor='',vencedor='';
  if(!b){status='BYE';idVencedor=a.id;vencedor=a.nome;}else{idJogo=gerarId_('J');gravarObjetoPrimeiraLinhaLivre_(SHEETS.JOGOS,'ID_JOGO',{ID_JOGO:idJogo,CATEGORIA:categoria,FASE:fase,GRUPO:'',RODADA:ordem,DATA:'',HORARIO_PREVISTO:'',MESA:'',ID_JOGADOR_A:a.id,JOGADOR_A:a.nome,ID_JOGADOR_B:b.id,JOGADOR_B:b.nome,SET1_A:'',SET1_B:'',SET2_A:'',SET2_B:'',SET3_A:'',SET3_B:'',SETS_A:'',SETS_B:'',PONTOS_A:'',PONTOS_B:'',ID_VENCEDOR:'',VENCEDOR:'',STATUS:'AGENDADO',OPERADOR_LANCAMENTO:'',DATA_HORA_LANCAMENTO:'',OBSERVACOES:'',SET4_A:'',SET4_B:'',SET5_A:'',SET5_B:'',TIPO_RESULTADO:'',MELHOR_DE:melhorDePorFase_(fase)});}
  gravarObjetoPrimeiraLinhaLivre_(SHEETS.MATA_MATA,'ID_CONFRONTO',{ID_CONFRONTO:idConfronto,CATEGORIA:categoria,FASE:fase,ORDEM:ordem,ORIGEM_JOGADOR_A:origemA||'',ID_JOGADOR_A:a.id,JOGADOR_A:a.nome,ORIGEM_JOGADOR_B:origemB||'',ID_JOGADOR_B:b?b.id:'',JOGADOR_B:b?b.nome:'BYE',ID_JOGO:idJogo,ID_VENCEDOR:idVencedor,VENCEDOR:vencedor,PROXIMO_CONFRONTO:'',STATUS:status,ID_PERDEDOR:'',PERDEDOR:'',DATA_GERACAO:agora,OBSERVACOES:obs||''});return idConfronto;
}
function listarMataMata_(){const sh=getSheet_(SHEETS.MATA_MATA),h=getHeaders_(sh),idx=indexHeaders_(h),last=sh.getLastRow();if(last<2)return [];return sh.getRange(2,1,last-1,h.length).getValues().filter(r=>String(r[idx.ID_CONFRONTO]||'').trim()).map(r=>({id:r[idx.ID_CONFRONTO],categoria:r[idx.CATEGORIA],fase:String(r[idx.FASE]||''),ordem:Number(r[idx.ORDEM]||0),origemA:r[idx.ORIGEM_JOGADOR_A],idA:r[idx.ID_JOGADOR_A],jogadorA:r[idx.JOGADOR_A],origemB:r[idx.ORIGEM_JOGADOR_B],idB:r[idx.ID_JOGADOR_B],jogadorB:r[idx.JOGADOR_B],idJogo:r[idx.ID_JOGO],idVencedor:r[idx.ID_VENCEDOR],vencedor:r[idx.VENCEDOR],proximo:r[idx.PROXIMO_CONFRONTO],status:String(r[idx.STATUS]||''),idPerdedor:idx.ID_PERDEDOR!==undefined?r[idx.ID_PERDEDOR]:'',perdedor:idx.PERDEDOR!==undefined?r[idx.PERDEDOR]:'',dataGeracao:idx.DATA_GERACAO!==undefined?r[idx.DATA_GERACAO]:'',observacoes:idx.OBSERVACOES!==undefined?r[idx.OBSERVACOES]:''})).sort((a,b)=>String(a.categoria).localeCompare(String(b.categoria))||ordemFase_(a.fase)-ordemFase_(b.fase)||a.ordem-b.ordem)}
function ordemFase_(fase){const f=String(fase||'').toUpperCase();if(f.startsWith('MATA_MATA_')||f==='DEZESSEIS_AVOS')return 1;if(f==='OITAVAS_DE_FINAL')return 2;if(f==='QUARTAS_DE_FINAL')return 3;if(f==='SEMIFINAL')return 4;if(f==='TERCEIRO_LUGAR')return 5;if(f==='FINAL')return 6;return 0}
function sincronizarConfrontoResultado_(idJogo,resultado){const sh=getSheet_(SHEETS.MATA_MATA),h=getHeaders_(sh),idx=indexHeaders_(h),last=sh.getLastRow();if(last<2)return;const vals=sh.getRange(2,1,last-1,h.length).getValues();for(let i=0;i<vals.length;i++){if(String(vals[i][idx.ID_JOGO])===String(idJogo)){const linha=i+2;sh.getRange(linha,idx.ID_VENCEDOR+1).setValue(resultado.idVencedor||'');sh.getRange(linha,idx.VENCEDOR+1).setValue(resultado.vencedor||'');sh.getRange(linha,idx.STATUS+1).setValue('FINALIZADO');if(idx.ID_PERDEDOR!==undefined)sh.getRange(linha,idx.ID_PERDEDOR+1).setValue(resultado.idPerdedor||'');if(idx.PERDEDOR!==undefined)sh.getRange(linha,idx.PERDEDOR+1).setValue(resultado.perdedor||'');break}}}
function avancarMataMataSePronto_(categoria,fase,usuario){
  if(String(getConfig_('GERACAO_PROXIMA_FASE_AUTOMATICA')||'TRUE').toUpperCase()==='FALSE')return;fase=String(fase||'').toUpperCase();if(fase==='FINAL'||fase==='TERCEIRO_LUGAR')return;const atual=listarMataMata_().filter(x=>x.categoria===categoria&&x.fase===fase);if(!atual.length||atual.some(x=>!['FINALIZADO','BYE'].includes(x.status)))return;const winners=atual.sort((a,b)=>a.ordem-b.ordem).filter(x=>x.idVencedor).map(x=>({id:x.idVencedor,nome:x.vencedor,origem:'Vencedor '+nomeFaseCurto_(fase)+' '+x.ordem,from:x.id}));if(!winners.length)return;
  if(fase==='SEMIFINAL'){
    if(winners.length===1){if(!listarMataMata_().some(x=>x.categoria===categoria&&x.fase==='FINAL'))criarConfronto_(categoria,'FINAL',1,winners[0],null,winners[0].origem,'BYE','Final decidida por avanço automático após ausência dupla no outro confronto.');return;}
    if(!listarMataMata_().some(x=>x.categoria===categoria&&x.fase==='FINAL')){const idFinal=criarConfronto_(categoria,'FINAL',1,winners[0],winners[1],winners[0].origem,winners[1].origem,'Final gerada automaticamente após as semifinais.');atual.forEach(x=>atualizarProximoConfronto_(x.id,idFinal));}
    const disputa=String(getConfig_('DISPUTA_TERCEIRO_LUGAR')||'TRUE').toUpperCase()!=='FALSE',losers=atual.filter(x=>x.idPerdedor).sort((a,b)=>a.ordem-b.ordem).map(x=>({id:x.idPerdedor,nome:x.perdedor,origem:'Perdedor Semifinal '+x.ordem,from:x.id}));if(disputa&&losers.length===2&&!listarMataMata_().some(x=>x.categoria===categoria&&x.fase==='TERCEIRO_LUGAR'))criarConfronto_(categoria,'TERCEIRO_LUGAR',1,losers[0],losers[1],losers[0].origem,losers[1].origem,'Disputa de terceiro lugar gerada automaticamente.');return;
  }
  const prox=fasePorQuantidade_(winners.length);if(listarMataMata_().some(x=>x.categoria===categoria&&x.fase===prox))return;for(let i=0;i<winners.length;i+=2){const a=winners[i],b=winners[i+1]||null,id=criarConfronto_(categoria,prox,(i/2)+1,a,b,a.origem,b?b.origem:'BYE','Fase seguinte gerada automaticamente.');atualizarProximoConfronto_(a.from,id);if(b)atualizarProximoConfronto_(b.from,id);}if(winners.length===1||winners.length%2===1)avancarMataMataSePronto_(categoria,prox,usuario);
}
function atualizarProximoConfronto_(id,proximo){const sh=getSheet_(SHEETS.MATA_MATA),h=getHeaders_(sh),idx=indexHeaders_(h),linha=localizarLinhaPorValor_(sh,idx.ID_CONFRONTO+1,id);if(linha!==-1)sh.getRange(linha,idx.PROXIMO_CONFRONTO+1).setValue(proximo||'')}
function nomeFaseCurto_(fase){return {QUARTAS_DE_FINAL:'Quartas',OITAVAS_DE_FINAL:'Oitavas',DEZESSEIS_AVOS:'16 avos',SEMIFINAL:'Semifinal'}[fase]||fase}
function existeFasePosteriorGerada_(categoria,fase){const ordem=ordemFase_(fase);return listarMataMata_().some(x=>x.categoria===categoria&&ordemFase_(x.fase)>ordem&&x.fase!=='TERCEIRO_LUGAR')}
function limparJogosMataMataCategoria_(categoria){const sh=getSheet_(SHEETS.JOGOS),h=getHeaders_(sh),idx=indexHeaders_(h),last=sh.getLastRow();if(last<2)return;const vals=sh.getRange(2,1,last-1,h.length).getValues();for(let i=vals.length-1;i>=0;i--){if(String(vals[i][idx.CATEGORIA])===categoria&&String(vals[i][idx.FASE])!=='GRUPOS')sh.getRange(i+2,1,1,h.length).clearContent()}}

function listarGruposPublicos_(){const cats=categoriasPermitidas_(),out=[];cats.forEach(c=>{const linhas=obterLinhasGrupo_(c),gr={};linhas.forEach(x=>{if(!gr[x.nomeGrupo])gr[x.nomeGrupo]=[];gr[x.nomeGrupo].push({id:x.idParticipante,nome:x.nomeParticipante,cabecaDeChave:x.cabecaDeChave})});Object.keys(gr).sort().forEach(nome=>out.push({categoria:c,grupo:nome,participantes:gr[nome]}))});return out}
function letraGrupo_(i){let s='';i++;while(i>0){i--;s=String.fromCharCode(65+(i%26))+s;i=Math.floor(i/26)}return s}
function slugCategoria_(c){return c.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'').slice(0,6)}
function configKeyCategoria_(c){return String(c||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
function getClassificadosPorGrupo_(categoria){const esp=Number(getConfig_('CLASSIFICADOS_POR_GRUPO_'+configKeyCategoria_(categoria))),geral=Number(getConfig_('CLASSIFICADOS_POR_GRUPO')||2);return Number.isInteger(esp)&&esp>0?esp:(Number.isInteger(geral)&&geral>0?geral:2)}
function obterLinhasGrupo_(categoria){const sh=getSheet_(SHEETS.GRUPOS),h=getHeaders_(sh),idx=indexHeaders_(h),last=sh.getLastRow();if(last<2)return [];return sh.getRange(2,1,last-1,h.length).getValues().filter(r=>String(r[idx.CATEGORIA])===categoria&&String(r[idx.ID_PARTICIPANTE]||'').trim()).map(r=>({idGrupo:r[idx.ID_GRUPO],categoria:r[idx.CATEGORIA],nomeGrupo:r[idx.NOME_GRUPO],ordem:Number(r[idx.ORDEM]),idParticipante:r[idx.ID_PARTICIPANTE],nomeParticipante:r[idx.NOME_PARTICIPANTE],posicaoSorteio:Number(r[idx.POSICAO_SORTEIO]||0),cabecaDeChave:r[idx.CABECA_DE_CHAVE]===true||String(r[idx.CABECA_DE_CHAVE]).toUpperCase()==='TRUE',status:String(r[idx.STATUS]||'')}))}
function limparLinhasPorCategoria_(aba,categoria,coluna){const sh=getSheet_(aba),h=getHeaders_(sh),idx=indexHeaders_(h),last=sh.getLastRow();if(last<2)return;const vals=sh.getRange(2,1,last-1,h.length).getValues();for(let i=vals.length-1;i>=0;i--)if(String(vals[i][idx[coluna]])===categoria)sh.getRange(i+2,1,1,h.length).clearContent()}

function listarParticipantesPublicos_(){return obterParticipantesValidos_().filter(p=>p.ativo&&p.statusInscricao==='APROVADO').map(p=>({id:p.id,nome:p.nome,turma:p.turma,categoria:p.categoriaValidada||p.categoriaEscolhida,status:p.statusInscricao}))}
function listarParticipantesAdmin_(){return obterParticipantesValidos_().filter(p=>p.ativo).map(p=>({id:p.id,dataInscricao:p.dataInscricao,nome:p.nome,turma:p.turma,modulo:p.modulo,email:p.email,categoriaEscolhida:p.categoriaEscolhida,categoriaValidada:p.categoriaValidada,statusRevisao:p.statusRevisao,statusInscricao:p.statusInscricao,cabecaDeChave:p.cabecaDeChave,ordemCabecaChave:p.ordemCabecaChave,ranking:p.ranking,observacoes:p.observacoes}))}
function obterParticipantesValidos_(){const sh=getSheet_(SHEETS.PARTICIPANTES),vals=sh.getRange(1,1,sh.getMaxRows(),sh.getLastColumn()).getValues(),idx=indexHeaders_(vals[0].map(String));return vals.slice(1).filter(r=>String(r[idx.ID_PARTICIPANTE]||'').trim()).map(r=>({id:r[idx.ID_PARTICIPANTE],dataInscricao:r[idx.DATA_INSCRICAO],nome:r[idx.NOME_COMPLETO],turma:r[idx.TURMA],modulo:r[idx.MODULO],email:r[idx.EMAIL],categoriaEscolhida:r[idx.CATEGORIA_ESCOLHIDA],categoriaValidada:r[idx.CATEGORIA_VALIDADA],statusRevisao:r[idx.STATUS_REVISAO_CATEGORIA],statusInscricao:String(r[idx.STATUS_INSCRICAO]||'').toUpperCase(),cabecaDeChave:r[idx.CABECA_DE_CHAVE]===true||String(r[idx.CABECA_DE_CHAVE]).toUpperCase()==='TRUE',ordemCabecaChave:r[idx.ORDEM_CABECA_CHAVE],ranking:r[idx.RANKING_ANTES_TORNEIO],observacoes:r[idx.OBSERVACOES],ativo:r[idx.ATIVO]===true||String(r[idx.ATIVO]).toUpperCase()==='TRUE'}))}
function emailJaInscrito_(email){return obterParticipantesValidos_().some(p=>p.ativo&&normalizarEmail_(p.email)===email)}
function categoriasPermitidas_(){return [String(getConfig_('CATEGORIA_1')||'Mesatenistas').trim(),String(getConfig_('CATEGORIA_2')||'Recreativo').trim()].filter(Boolean)}

function listarOperadores_(){const sh=getSheet_(SHEETS.OPERADORES),vals=sh.getRange(1,1,Math.max(sh.getLastRow(),1),sh.getLastColumn()).getValues(),idx=indexHeaders_(vals[0].map(String));return vals.slice(1).filter(r=>String(r[idx.ID_OPERADOR]||'').trim()).map(r=>({id:r[idx.ID_OPERADOR],nome:r[idx.NOME],email:r[idx.EMAIL],nivel:r[idx.NIVEL_ACESSO],status:r[idx.STATUS],dataCadastro:r[idx.DATA_CADASTRO],ultimoLogin:r[idx.ULTIMO_LOGIN]}))}
function buscarOperadorPorEmail_(email){const sh=getSheet_(SHEETS.OPERADORES),h=getHeaders_(sh),idx=indexHeaders_(h),max=sh.getMaxRows();if(max<2)return null;const vals=sh.getRange(2,1,max-1,h.length).getValues();for(let i=0;i<vals.length;i++){const r=vals[i];if(normalizarEmail_(r[idx.EMAIL])===email&&String(r[idx.ID_OPERADOR]||'').trim())return {linha:i+2,id:r[idx.ID_OPERADOR],nome:r[idx.NOME],email:normalizarEmail_(r[idx.EMAIL]),nivel:String(r[idx.NIVEL_ACESSO]||'').toUpperCase(),status:String(r[idx.STATUS]||'').toUpperCase(),pinSalt:String(r[idx.PIN_SALT]||''),pinHash:String(r[idx.PIN_HASH]||'')}}return null}
function buscarOperadorPorId_(id){const sh=getSheet_(SHEETS.OPERADORES),h=getHeaders_(sh),idx=indexHeaders_(h),linha=localizarLinhaPorValor_(sh,idx.ID_OPERADOR+1,id);if(linha===-1)return null;const r=sh.getRange(linha,1,1,h.length).getValues()[0];return {linha,id:r[idx.ID_OPERADOR],nome:r[idx.NOME],email:normalizarEmail_(r[idx.EMAIL]),nivel:String(r[idx.NIVEL_ACESSO]||'').toUpperCase(),status:String(r[idx.STATUS]||'').toUpperCase()}}
function adminSalvarOperador_(d,usuario){const nome=limparTexto_(d.nome),email=normalizarEmail_(d.email),pin=String(d.pin||'').trim(),nivel=String(d.nivel||'OPERADOR').toUpperCase();if(!nome||!email||!pin)return {ok:false,erro:'CAMPOS_OBRIGATORIOS',mensagem:'Informe nome, e-mail e PIN.'};if(!emailValido_(email))return {ok:false,erro:'EMAIL_INVALIDO',mensagem:'Informe um e-mail válido.'};if(pin.length<6)return {ok:false,erro:'PIN_FRACO',mensagem:'O PIN deve ter pelo menos 6 caracteres.'};if(!['OPERADOR','ADMINISTRADOR'].includes(nivel))return {ok:false,erro:'NIVEL_INVALIDO',mensagem:'Nível de acesso inválido.'};if(buscarOperadorPorEmail_(email))return {ok:false,erro:'OPERADOR_EXISTENTE',mensagem:'Já existe um operador com este e-mail.'};const salt=gerarSalt_(),id=gerarId_('OP');gravarObjetoPrimeiraLinhaLivre_(SHEETS.OPERADORES,'ID_OPERADOR',{ID_OPERADOR:id,NOME:nome,EMAIL:email,NIVEL_ACESSO:nivel,STATUS:'ATIVO',DATA_CADASTRO:new Date(),OBSERVACOES:'Operador cadastrado pelo painel administrativo.',PIN_SALT:salt,PIN_HASH:hashPin_(salt,pin),ULTIMO_LOGIN:''});registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'OPERADOR_CADASTRADO',entidade:'OPERADORES',idRegistro:id,valorAnterior:'',valorNovo:JSON.stringify({nome,email,nivel}),observacoes:'Novo operador cadastrado.'});return {ok:true,mensagem:'Operador cadastrado com sucesso.'}}
function adminStatusOperador_(d,usuario){const id=limparTexto_(d.idOperador),status=String(d.status||'').toUpperCase();if(!['ATIVO','INATIVO'].includes(status))return {ok:false,erro:'STATUS_INVALIDO',mensagem:'Status do operador inválido.'};const op=buscarOperadorPorId_(id);if(!op)return {ok:false,erro:'OPERADOR_NAO_ENCONTRADO',mensagem:'Operador não encontrado.'};if(op.email===usuario.email&&status==='INATIVO')return {ok:false,erro:'AUTO_DESATIVACAO',mensagem:'Você não pode desativar o próprio usuário.'};const sh=getSheet_(SHEETS.OPERADORES),idx=indexHeaders_(getHeaders_(sh)),ant=sh.getRange(op.linha,idx.STATUS+1).getValue();sh.getRange(op.linha,idx.STATUS+1).setValue(status);registrarHistorico_({usuario:usuario.email,perfil:usuario.nivel,acao:'STATUS_OPERADOR_ALTERADO',entidade:'OPERADORES',idRegistro:id,valorAnterior:ant,valorNovo:status,observacoes:'Status de operador alterado.'});return {ok:true,mensagem:'Status do operador atualizado com sucesso.'}}
function atualizarUltimoLogin_(linha){const sh=getSheet_(SHEETS.OPERADORES),idx=indexHeaders_(getHeaders_(sh));sh.getRange(linha,idx.ULTIMO_LOGIN+1).setValue(new Date())}

function registrarHistorico_(d){gravarObjetoPrimeiraLinhaLivre_(SHEETS.HISTORICO,'ID_EVENTO',{ID_EVENTO:gerarId_('H'),DATA_HORA:new Date(),USUARIO:d.usuario||'',PERFIL:d.perfil||'',ACAO:d.acao||'',ENTIDADE:d.entidade||'',ID_REGISTRO:d.idRegistro||'',VALOR_ANTERIOR:d.valorAnterior||'',VALOR_NOVO:d.valorNovo||'',OBSERVACOES:d.observacoes||''})}
function gravarObjetoPrimeiraLinhaLivre_(aba,colunaId,obj){const sh=getSheet_(aba),h=getHeaders_(sh),idIndex=h.indexOf(colunaId);if(idIndex===-1)throw new Error('Coluna não encontrada: '+colunaId);const linha=primeiraLinhaLivrePorColuna_(sh,idIndex+1,2),row=h.map(x=>Object.prototype.hasOwnProperty.call(obj,x)?obj[x]:'');sh.getRange(linha,1,1,row.length).setValues([row])}
function primeiraLinhaLivrePorColuna_(sh,coluna,inicio){inicio=inicio||2;const max=sh.getMaxRows(),vals=sh.getRange(inicio,coluna,max-inicio+1,1).getDisplayValues().flat();for(let i=0;i<vals.length;i++)if(String(vals[i]).trim()==='')return inicio+i;sh.insertRowAfter(sh.getMaxRows());return sh.getMaxRows()}
function localizarLinhaPorValor_(sh,coluna,valor){const max=sh.getMaxRows();if(max<2)return -1;const vals=sh.getRange(2,coluna,max-1,1).getDisplayValues().flat();for(let i=0;i<vals.length;i++)if(String(vals[i]).trim()===String(valor).trim())return i+2;return -1}
function getConfig_(campo){const sh=getSheet_(SHEETS.CONFIG),last=sh.getLastRow();if(last<2)return '';const vals=sh.getRange(2,1,last-1,2).getValues();for(let i=0;i<vals.length;i++)if(String(vals[i][0]).trim()===campo)return vals[i][1];return ''}
function setConfig_(campo,valor,descricao){const sh=getSheet_(SHEETS.CONFIG),last=Math.max(sh.getLastRow(),1),vals=last>=2?sh.getRange(2,1,last-1,1).getDisplayValues().flat():[];for(let i=0;i<vals.length;i++){if(String(vals[i]).trim()===campo){sh.getRange(i+2,2).setValue(valor);if(descricao)sh.getRange(i+2,3).setValue(descricao);return}}sh.appendRow([campo,valor,descricao||''])}
function getSheet_(nome){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(nome);if(!sh)throw new Error('Aba não encontrada: '+nome);return sh}
function getHeaders_(sh){return sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(x=>String(x).trim())}
function indexHeaders_(h){const idx={};h.forEach((x,i)=>idx[String(x).trim()]=i);return idx}
function gerarSalt_(){return Utilities.getUuid().replace(/-/g,'')}
function hashPin_(salt,pin){return hashTexto_(String(salt)+String(pin))}
function hashTexto_(texto){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(texto),Utilities.Charset.UTF_8).map(b=>('0'+((b<0?b+256:b).toString(16))).slice(-2)).join('')}
function parsePayload_(e){if(!e)return {};if(e.postData&&e.postData.contents&&String(e.postData.type||'').toLowerCase().includes('application/json'))return JSON.parse(e.postData.contents);return e.parameter||{}}
function limparTexto_(v){return String(v||'').trim().replace(/\s+/g,' ')}
function normalizarEmail_(v){return String(v||'').trim().toLowerCase()}
function emailValido_(e){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)}
function gerarId_(prefixo){const d=Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'America/Sao_Paulo','yyyyMMddHHmmss'),r=Math.floor(1000+Math.random()*9000);return prefixo+'-'+d+'-'+r}
function jsonResponse_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function erroJson_(err){const m=String(err&&err.message?err.message:err),p=m.split('|');if(p.length>1)return jsonResponse_({ok:false,erro:p.shift(),mensagem:p.join('|')});return jsonResponse_({ok:false,erro:'ERRO_INTERNO',mensagem:m})}